steps: 
- id: 'branch name'
  name: gcr.io/cloud-builders/git
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      branch=$(basename "$_REF")
      git checkout ${branch}
      echo "***********************"
      git branch --show-current
      echo 
      
# Step 1: Initialize Terraform    
- name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        terraform init
# Step 2: Terraform Plan
- name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        terraform plan -out=tfplan
       
logsBucket: 'gs://logs-cb-cloudbuild'
options:
    logging: GCS_ONLY
